apiVersion: v1
kind: Service
metadata:
  labels:
    app: swisschain-service-name-worker
    environment: Development
  name: swisschain-service-name-worker
  namespace: swisschain-product-name
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: swisschain-service-name-worker
  sessionAffinity: None
  type: ClusterIP
