apiVersion: v1
data:
  RemoteSettingsUrl: <Base64 encoded settings url>
  # http://settings.common.svc.cluster.local/product-namespace/service-example
kind: Secret
metadata:
  name: swisschain-service-name
  namespace: swisschain-product-name
type: Opaque
