apiVersion: v1
kind: Service
metadata:
  labels:
    app: swisschain-service-name-api
    environment: Development
  name: swisschain-service-name-api
  namespace: swisschain-product-name
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  - name: grpc
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: swisschain-service-name-api
  sessionAffinity: None
  type: ClusterIP
