name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release "template/Service.Example.sln"
    - name: Test
      run: dotnet test --configuration Release "template/Service.Example.sln"
    - name: Publish
      run: dotnet publish ./template/src/Example/Example.csproj --output ./publish --configuration Release /p:AssemblyVersion=1.0.0
    - name: Check dir
      run: ls ./publish