name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build
      run: dotnet build --configuration Release "template/Service.ServiceName.sln"
    - name: Test
      run: dotnet test --no-build --configuration Release "template/Service.ServiceName.sln"
    - name: Publish API
      run: dotnet publish --no-build ./template/src/ServiceName/ServiceName.csproj --output ./publish-api --configuration Release /p:AssemblyVersion=0.0.0
    - name: Publish worker
      run: dotnet publish --no-build ./template/src/ServiceName.Worker/ServiceName.Worker.csproj --output ./publish-worker --configuration Release /p:AssemblyVersion=0.0.0
    - name: Check api dir
      run: ls ./publish-api
    - name: Check worker dir
      run: ls ./publish-worker